export const UI_COPY = {
  es: {
    title: "Flux Basin",
    subtitle: "Arcade original de fisica tactil con orbita, rebote y captura magnetica.",
    worldLabel: "Mundo 1 · Fundicion Neon",
    labels: {
      play: "Jugar",
      continue: "Continuar",
      levelSelect: "Seleccion de niveles",
      backMenu: "Menu",
      nextLevel: "Siguiente",
      retry: "Retry",
      restart: "Reiniciar",
      pause: "Pausa",
      resume: "Seguir",
      fullscreen: "Pantalla completa",
      skin: "Skin",
      audio: "Audio",
      vibration: "Vibracion",
      assist: "Ayuda visual",
      sensitivity: "Sensibilidad",
      autoRetry: "Auto retry",
      level: "Nivel",
      stars: "Estrellas",
      best: "Mejor",
      attempts: "Intentos",
      rebounds: "Rebotes",
      time: "Tiempo",
      settings: "Ajustes",
      objective: "Objetivo",
    },
    sections: {
      menuTagline: "Tira hacia atras, suelta y deja que la fisica haga el resto.",
      objective: "Introduce la orbita en la capsula receptora. El juego premia precision, limpieza y pocos intentos.",
      worldSummary: "20 niveles cortos en un laboratorio neon-industrial, con curva progresiva y reinicio instantaneo.",
      settingsHint: "Perfil Comfort amplifica la ayuda visual y reduce sensibilidad para mejorar control tactil.",
      controls: "Touch: arrastra desde la orbita hacia atras y suelta. Teclado: flechas/A-D apuntan, W/S potencia, Enter/Espacio lanza, P pausa, R reinicia, M audio, F pantalla completa.",
      controlsTouch: "Touch: arrastra desde la orbita hasta el punto al que quieres enviar el tiro y suelta. La linea marca la direccion final y la distancia del gesto define la fuerza.",
    },
    messages: {
      menu: "Sesion lista. Continúa la campaña o elige un nivel desbloqueado.",
      ready: "Tira hacia atras y suelta. La previsualizacion marca la trayectoria estimada del tiro.",
      readyTouch: "Arrastra desde la orbita hasta el punto final del tiro y suelta. En movil y tablet la linea que marcas define direccion y fuerza, sin trayectorias punteadas.",
      retry: "Reintento instantaneo listo.",
      paused: "Simulacion pausada.",
      resume: "Simulacion reanudada.",
      soundOn: "Audio activado.",
      soundOff: "Audio silenciado.",
      inFlight: "Orbita en vuelo.",
      nearMiss: "Casi. El borde magnetico la rozó.",
      perfectBounce: "Rebote perfecto.",
      skinUnlocked: "Nueva skin desbloqueada.",
      worldClear: "Mundo completado. La Fundicion Neon ha quedado dominada.",
    },
    resultLabels: {
      success: "Capsula asegurada",
      out: "Fuera de limites",
      hazard: "Hazard letal",
      timeout: "Tiempo agotado",
      stuck: "Orbita bloqueada",
    },
    medals: {
      silk: "Linea de Seda",
      flash: "Clear Relampago",
      stable: "Captura Estable",
    },
    toggles: {
      on: "On",
      off: "Off",
      standard: "Standard",
      comfort: "Comfort",
    },
  },
  en: {
    title: "Flux Basin",
    subtitle: "Original tactile physics arcade about orbit, rebound and magnetic capture.",
    worldLabel: "World 1 · Neon Foundry",
    labels: {
      play: "Play",
      continue: "Continue",
      levelSelect: "Level select",
      backMenu: "Menu",
      nextLevel: "Next",
      retry: "Retry",
      restart: "Restart",
      pause: "Pause",
      resume: "Resume",
      fullscreen: "Fullscreen",
      skin: "Skin",
      audio: "Audio",
      vibration: "Vibration",
      assist: "Visual help",
      sensitivity: "Sensitivity",
      autoRetry: "Auto retry",
      level: "Level",
      stars: "Stars",
      best: "Best",
      attempts: "Attempts",
      rebounds: "Bounces",
      time: "Time",
      settings: "Settings",
      objective: "Objective",
    },
    sections: {
      menuTagline: "Pull back, release, and let readable physics do the rest.",
      objective: "Sink the orb into the receiving capsule. The game rewards precision, cleanliness, and low-attempt clears.",
      worldSummary: "20 short levels in a neon-industrial lab with progressive difficulty and instant retry.",
      settingsHint: "Comfort profile adds stronger visual assistance and lower sensitivity for steadier touch play.",
      controls: "Touch: pull back from the orb and release. Keyboard: arrows/A-D aim, W/S power, Enter/Space fire, P pause, R restart, M audio, F fullscreen.",
      controlsTouch: "Touch: drag from the orb to the point where you want the shot to go, then release. The line sets the final direction and the swipe distance sets the force.",
    },
    messages: {
      menu: "Session ready. Continue the campaign or open any unlocked level.",
      ready: "Pull back and release. The preview shows the estimated shot arc.",
      readyTouch: "Drag from the orb to the final shot point and release. On mobile and tablet the line you draw defines direction and force, without dotted trajectories.",
      retry: "Instant retry armed.",
      paused: "Simulation paused.",
      resume: "Simulation resumed.",
      soundOn: "Audio enabled.",
      soundOff: "Audio muted.",
      inFlight: "Orb in flight.",
      nearMiss: "Close. The magnetic rim almost caught it.",
      perfectBounce: "Perfect bank.",
      skinUnlocked: "New skin unlocked.",
      worldClear: "World completed. Neon Foundry is mastered.",
    },
    resultLabels: {
      success: "Capsule secured",
      out: "Out of bounds",
      hazard: "Hazard hit",
      timeout: "Time expired",
      stuck: "Orb got stuck",
    },
    medals: {
      silk: "Silk Line",
      flash: "Flash Clear",
      stable: "Stable Catch",
    },
    toggles: {
      on: "On",
      off: "Off",
      standard: "Standard",
      comfort: "Comfort",
    },
  },
};

export function localize(copy, locale) {
  return copy[locale] ?? copy.en;
}
