export const UI_COPY = {
  es: {
    title: "Bowling Pro Tour",
    subtitle:
      "Rebuild del arcade de bolos con entorno inspirado en el pack de Blender, marcador oficial de 10 cuadros y reglamento visible dentro del juego.",
    start: "Empezar serie",
    restart: "Nueva serie",
    fullscreen: "Pantalla completa",
    aiDifficulty: "Dificultad IA",
    aiPlayers: "IAs en partida",
    lanePair: "Par de pistas",
    lanePairValue: "Se alterna A/B cada cuadro, como en juego de liga o torneo.",
    controls: "Ajuste de lanzamiento",
    shoot: "Lanzar bola",
    resetAim: "Centrar linea",
    aim: "Linea",
    power: "Potencia",
    spin: "Efecto",
    loft: "Altura",
    player: "Jugador",
    total: "Total",
    frame: "Cuadro",
    lane: "Pista",
    status: "Estado",
    scoreboard: "Marcador oficial",
    matchDesk: "Cabina de serie",
    assetPack: "Assets y entorno",
    rulebook: "Reglamento",
    simulated: "Simulada",
    partial: "Parcial",
    documented: "Documentada",
    telemetry: "Telemetria",
    aiDesk: "Lectura IA",
    thinking: "Pensando",
    ready: "Listo",
    confidence: "Confianza",
    target: "Linea objetivo",
    livePins: "Bolos en pie",
    lastRoll: "Ultimo tiro",
    strike: "Pleno",
    spare: "Semipleno",
    open: "Abierto",
    foul: "Falta",
    split: "Split",
    legal: "Legal",
    illegal: "Ilegal",
    winner: "Ganador",
    tie: "Empate",
    yourTurn: "Tu turno",
    aiTurn: "Turno IA",
    turnLights: "Luces de turno",
    menuHint:
      "Configura la dificultad y cuantas IAs participan, revisa el reglamento o el pack de referencia y empieza la serie. Usa A/D para linea, W/S para potencia, Q/E para efecto, Z/X para altura y Espacio para lanzar.",
    finishedHint:
      "Serie cerrada. Puedes revisar cuadro a cuadro, cambiar de dificultad o reiniciar otra serie de 10 cuadros.",
    help:
      "Teclado: A/D linea, W/S potencia, Q/E efecto, Z/X altura, Enter/Espacio lanzar, R nueva serie, F pantalla completa.",
    summary: "Resumen de partida",
    activePlayer: "Jugador activo",
    nextUp: "Siguiente accion",
    ruleCoverage: "Cobertura reglamentaria",
    sourcePack: "Pack de referencia",
    sourceRepo: "Repositorio origen",
    sourceLicense: "Licencia",
    fileInventory: "Inventario de ficheros",
    environmentCues: "Claves de entorno extraidas",
    implementationNotes: "Como se implemento en navegador",
    materials: "Materiales interpretados",
    stats: "Ritmo de serie",
    doubles: "Dobles",
    triples: "Triples",
    bestRun: "Racha X",
    opens: "Abiertos",
    framesWon: "Frames cerrados",
    official: "Oficial",
    repoLinkLabel: "Abrir repo",
    docsLabel: "Notas del rebuild",
    rulesPanelHint:
      "El juego aplica la parte jugable del reglamento y documenta el resto de reglas de arbitraje y competición.",
    assetsPanelHint:
      "El entorno canvas toma como referencia el alley, la bola, el pin, el collider y la escena de fisicas del repositorio externo.",
    paletteNote: "Paleta aproximada deducida del pack y de los materiales de Unity opcionales.",
    foulMark: "Las faltas se marcan con F en el cuadro.",
    monitorLabel: "Broadcast alley",
  },
  en: {
    title: "Bowling Pro Tour",
    subtitle:
      "Rebuilt arcade bowling with an environment inspired by the Blender pack, official 10-frame scoring, and an in-game rulebook.",
    start: "Start series",
    restart: "New series",
    fullscreen: "Fullscreen",
    aiDifficulty: "AI difficulty",
    aiPlayers: "AI players",
    lanePair: "Lane pair",
    lanePairValue: "The game alternates lane A/B every frame, like league or tournament play.",
    controls: "Shot setup",
    shoot: "Throw ball",
    resetAim: "Center line",
    aim: "Line",
    power: "Power",
    spin: "Spin",
    loft: "Loft",
    player: "Player",
    total: "Total",
    frame: "Frame",
    lane: "Lane",
    status: "Status",
    scoreboard: "Official scoreboard",
    matchDesk: "Series desk",
    assetPack: "Assets and environment",
    rulebook: "Rulebook",
    simulated: "Simulated",
    partial: "Partial",
    documented: "Documented",
    telemetry: "Telemetry",
    aiDesk: "AI readout",
    thinking: "Thinking",
    ready: "Ready",
    confidence: "Confidence",
    target: "Target line",
    livePins: "Pins standing",
    lastRoll: "Last roll",
    strike: "Strike",
    spare: "Spare",
    open: "Open",
    foul: "Foul",
    split: "Split",
    legal: "Legal",
    illegal: "Illegal",
    winner: "Winner",
    tie: "Tie",
    yourTurn: "Your turn",
    aiTurn: "AI turn",
    turnLights: "Turn lights",
    menuHint:
      "Set the difficulty and how many AI players join, review the rulebook or source pack, and start the series. Use A/D for line, W/S for power, Q/E for spin, Z/X for loft, and Space to throw.",
    finishedHint:
      "Series finished. Review the frames, switch difficulty, or restart another 10-frame set.",
    help:
      "Keyboard: A/D line, W/S power, Q/E spin, Z/X loft, Enter/Space throw, R new series, F fullscreen.",
    summary: "Match summary",
    activePlayer: "Active player",
    nextUp: "Next action",
    ruleCoverage: "Rules coverage",
    sourcePack: "Reference pack",
    sourceRepo: "Source repository",
    sourceLicense: "License",
    fileInventory: "File inventory",
    environmentCues: "Extracted environment cues",
    implementationNotes: "Browser implementation",
    materials: "Interpreted materials",
    stats: "Series pace",
    doubles: "Doubles",
    triples: "Triples",
    bestRun: "Strike run",
    opens: "Opens",
    framesWon: "Closed frames",
    official: "Official",
    repoLinkLabel: "Open repo",
    docsLabel: "Rebuild notes",
    rulesPanelHint:
      "The game enforces the playable rules and documents the remaining officiating and competition clauses.",
    assetsPanelHint:
      "The canvas environment is based on the alley, ball, pin, collider, and fun-with-physics scene from the external repository.",
    paletteNote: "Approximate palette interpreted from the pack and the optional Unity materials.",
    foulMark: "Fouls are shown as F on the score sheet.",
    monitorLabel: "Broadcast alley",
  },
};

export function localizeLabel(label, locale) {
  if (!label) {
    return "";
  }
  if (typeof label === "string") {
    return label;
  }
  return label[locale] ?? label.es ?? label.en ?? "";
}
