export const OBSTACLE_LIBRARY = {
  wall: {
    collider: "rect",
    renderLayer: "solid",
    material: "metal",
    restitution: 0.76,
    vfx: "spark",
    sfx: "metal-soft",
  },
  ramp: {
    collider: "segment",
    renderLayer: "solid",
    material: "metal",
    restitution: 0.8,
    vfx: "spark",
    sfx: "metal-soft",
  },
  bumper: {
    collider: "circle",
    renderLayer: "interactive",
    material: "rubber",
    restitution: 1.08,
    vfx: "pulse-ring",
    sfx: "rubber-strong",
  },
  movingBar: {
    collider: "rect",
    renderLayer: "interactive",
    material: "composite",
    restitution: 0.88,
    vfx: "streak",
    sfx: "composite",
  },
  spikeStrip: {
    collider: "hazardRect",
    renderLayer: "hazard",
    material: "hazard",
    restitution: 0.2,
    vfx: "hazard-burst",
    sfx: "hazard",
  },
  fan: {
    collider: "zoneRect",
    renderLayer: "field",
    material: "air",
    vfx: "wind-ribbon",
    sfx: "fan",
  },
  stickyPad: {
    collider: "rect",
    renderLayer: "surface",
    material: "gel",
    restitution: 0.54,
    vfx: "goo",
    sfx: "gel",
  },
  gravityWell: {
    collider: "zoneCircle",
    renderLayer: "field",
    material: "gravity",
    vfx: "gravity-ring",
    sfx: "gravity",
  },
  portal: {
    collider: "zoneCircle",
    renderLayer: "interactive",
    material: "energy",
    vfx: "portal-flare",
    sfx: "portal",
  },
  gate: {
    collider: "rect",
    renderLayer: "timed",
    material: "metal",
    restitution: 0.82,
    vfx: "gate-flash",
    sfx: "gate",
  },
};

export const OBSTACLE_TYPE_ORDER = Object.keys(OBSTACLE_LIBRARY);
